matrix:
  - name: Markdown
    aspell:
      mode: none
      lang: en_US
    dictionary:
      wordlists:
        - .spellcheck.words.txt
      output: wordlist.dic
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.html:
          comments: false
          attributes:
            - title
            - alt
          ignores:
            - :matches(code, pre)
            - pre
            - code
            - li
            - h1
            - h2
            - h3
            - h4
    sources:
      - 'docs/**/*.md'
  - name: 'TypeScript/JS Strings & Comments'
    aspell:
      mode: none
      lang: en_US
    sources:
      - '**/*.d.ts'
      - '**/*.tsx'
      - '**/*.ts'
      - '**/*.js'
    dictionary:
      wordlists:
        - .spellcheck.words.txt
      output: wordlist.dic
      encoding: utf-8
    pipeline:
      - pyspelling.filters.javascript:
          jsdocs: true
          line_comments: false
          block_comments: false
