matrix:
  - name: Markdown
    spellchecker: hunspell
    hunspell:
      d: en_US,./wordlist
    dictionary:
      wordlists:
        - .spellcheck.words.txt
      output: wordlist.dic
      encoding: utf-8
    pipeline:
      - pyspelling.filters.url:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - markdown.extensions.fenced_code
            - markdown.extensions.tables
      - pyspelling.filters.html:
          comments: false
          attributes:
            - title
            - alt
          ignores:
            - :matches(code, pre)
            - pre
            - code
            - li
            - h1
            - h2
            - h3
            - h4
    sources:
      - 'docs/**/*.md'
  - name: 'TypeScript/JS Strings & Comments'
    spellchecker: hunspell
    hunspell:
      d: en_US,./wordlist
    sources:
      - '**/*.d.ts'
      - '**/*.tsx'
      - '**/*.ts'
      - '**/*.js'
    dictionary:
      wordlists:
        - .spellcheck.words.txt
      output: wordlist.dic
      encoding: utf-8
    pipeline:
      - pyspelling.filters.url:
      - pyspelling.filters.javascript:
          jsdocs: true
          strings: false
          line_comments: false
          block_comments: false
