compressionLevel: mixed

enableGlobalCache: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

plugins:
  - checksum: 67ce9e30cf152af35d3dc292f915cb39220942f5f406211801da2b721d873857f8ea6d9c57893e1295133f5d128fa6388bf16a4610ef788f30e987e58f84db26
    path: .yarn/plugins/@yarnpkg/plugin-postinstall-dev.cjs
    spec: 'https://raw.githubusercontent.com/sachinraja/yarn-plugin-postinstall-dev/main/bundles/%40yarnpkg/plugin-postinstall-dev.js'

yarnPath: .yarn/releases/yarn-4.14.1.cjs

npmMinimalAgeGate: 7d

# In case you must have a package version that would be disallowed
# by the above npmMinimalAgeGate
npmPreapprovedPackages:
  - '@firebase/ai@2.14.0'
  - '@firebase/analytics-compat@0.2.29'
  - '@firebase/analytics-types@0.8.4'
  - '@firebase/analytics@0.10.23'
  - '@firebase/app-check-compat@0.4.6'
  - '@firebase/app-check-interop-types@0.3.4'
  - '@firebase/app-check-types@0.5.4'
  - '@firebase/app-check@0.13.0'
  - '@firebase/app-compat@0.5.16'
  - '@firebase/app-types@0.9.5'
  - '@firebase/app@0.16.0'
  - '@firebase/auth-compat@0.6.9'
  - '@firebase/auth-interop-types@0.2.5'
  - '@firebase/auth-types@0.13.1'
  - '@firebase/auth@1.13.4'
  - '@firebase/component@0.7.4'
  - '@firebase/data-connect@0.7.3'
  - '@firebase/database-compat@2.1.6'
  - '@firebase/database-types@1.0.21'
  - '@firebase/database@1.1.4'
  - '@firebase/firestore-compat@0.4.12'
  - '@firebase/firestore-types@3.0.4'
  - '@firebase/firestore@4.17.0'
  - '@firebase/functions-compat@0.4.6'
  - '@firebase/functions-types@0.6.4'
  - '@firebase/functions@0.13.6'
  - '@firebase/installations-compat@0.2.23'
  - '@firebase/installations-types@0.5.4'
  - '@firebase/installations@0.6.23'
  - '@firebase/logger@0.5.1'
  - '@firebase/messaging-compat@0.2.28'
  - '@firebase/messaging-interop-types@0.2.5'
  - '@firebase/messaging@0.13.1'
  - '@firebase/performance-compat@0.2.26'
  - '@firebase/performance-types@0.2.4'
  - '@firebase/performance@0.7.13'
  - '@firebase/remote-config-compat@0.2.28'
  - '@firebase/remote-config-types@0.5.1'
  - '@firebase/remote-config@0.9.1'
  - '@firebase/storage-compat@0.4.4'
  - '@firebase/storage-types@0.8.4'
  - '@firebase/storage@0.14.4'
  - '@firebase/util@1.15.2'
  - '@firebase/webchannel-wrapper@1.0.6'
  - '@react-native-firebase/*'
  - 'firebase@12.17.1' # If adopting recent firebase-js-sdk, specify directly here
  - 'react-native-coverage@0.2.0'
