compressionLevel: mixed

enableGlobalCache: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

plugins:
  - checksum: 67ce9e30cf152af35d3dc292f915cb39220942f5f406211801da2b721d873857f8ea6d9c57893e1295133f5d128fa6388bf16a4610ef788f30e987e58f84db26
    path: .yarn/plugins/@yarnpkg/plugin-postinstall-dev.cjs
    spec: 'https://raw.githubusercontent.com/sachinraja/yarn-plugin-postinstall-dev/main/bundles/%40yarnpkg/plugin-postinstall-dev.js'

yarnPath: .yarn/releases/yarn-4.14.1.cjs

npmMinimalAgeGate: 7d

# In case you must have a package version that would be disallowed
# by the above npmMinimalAgeGate
npmPreapprovedPackages:
  - '@firebase/ai@2.15.0'
  - '@firebase/analytics-compat@0.2.30'
  - '@firebase/analytics-types@0.8.5'
  - '@firebase/analytics@0.10.24'
  - '@firebase/app-check-compat@0.4.7'
  - '@firebase/app-check-interop-types@0.3.5'
  - '@firebase/app-check-types@0.5.5'
  - '@firebase/app-check@0.13.1'
  - '@firebase/app-compat@0.5.17'
  - '@firebase/app-types@0.9.6'
  - '@firebase/app@0.16.1'
  - '@firebase/auth-compat@0.6.10'
  - '@firebase/auth-interop-types@0.2.6'
  - '@firebase/auth-types@0.13.2'
  - '@firebase/auth@1.13.5'
  - '@firebase/component@0.7.5'
  - '@firebase/data-connect@0.7.4'
  - '@firebase/database-compat@2.1.7'
  - '@firebase/database-types@1.0.22'
  - '@firebase/database@1.1.5'
  - '@firebase/firestore-compat@0.4.13'
  - '@firebase/firestore-types@3.0.5'
  - '@firebase/firestore@4.17.1'
  - '@firebase/functions-compat@0.5.0'
  - '@firebase/functions-types@0.6.5'
  - '@firebase/functions@0.14.0'
  - '@firebase/installations-compat@0.2.24'
  - '@firebase/installations-types@0.5.5'
  - '@firebase/installations@0.6.24'
  - '@firebase/logger@0.5.2'
  - '@firebase/messaging-compat@0.2.29'
  - '@firebase/messaging-interop-types@0.2.6'
  - '@firebase/messaging@0.13.2'
  - '@firebase/performance-compat@0.2.27'
  - '@firebase/performance-types@0.2.5'
  - '@firebase/performance@0.7.14'
  - '@firebase/remote-config-compat@0.2.29'
  - '@firebase/remote-config-types@0.5.2'
  - '@firebase/remote-config@0.9.2'
  - '@firebase/storage-compat@0.4.5'
  - '@firebase/storage-types@0.8.5'
  - '@firebase/storage@0.14.5'
  - '@firebase/util@1.15.3'
  - '@firebase/webchannel-wrapper@1.0.7'
  - '@react-native-firebase/*'
  - 'firebase@12.18.0' # If adopting recent firebase-js-sdk, specify directly here
