codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "40...100"

  status:
    project: yes
    patch: yes
    changes: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
