/**
 * The code here-in is private and copyright Invertase Limited.
 *
 * Commercial use, Distribution, Modification, Patent use and Private use is NOT permitted except for usage by
 * Invertase and it's React Native Firebase product only.
 *
 * Specifically; you are NOT permitted to use, copy or modify this code in any form except in circumstances where it's usage is only for
 * the benefit of, and contributing to, the React Native Firebase product by Invertase, or; you have been permitted to do
 * so in writing by Invertase expressly (knowledge of use does not imply permission granted).
 *
 */
// TODO move to external lib
// prettier-ignore
"use strict";var e=this&&this.t||function(o,u,c,s){return new(c=c||Promise)(function(n,t){function e(n){try{i(s.next(n))}catch(n){t(n)}}function r(n){try{i(s.throw(n))}catch(n){t(n)}}function i(t){t.done?n(t.value):new c(function(n){n(t.value)}).then(e,r)}i((s=s.apply(o,u||[])).next())})},u=this&&this.i||function(e,r){var i,o,u,n,c={label:0,o:function(){if(1&u[0])throw u[1];return u[1]},u:[],s:[]};return n={next:t(0),throw:t(1),return:t(2)},"function"==typeof Symbol&&(n[Symbol.iterator]=function(){return this}),n;function t(t){return function(n){return function(t){if(i)throw new TypeError("Generator is already executing.");for(;c;)try{if(i=1,o&&(u=2&t[0]?o.return:t[0]?o.throw||((u=o.return)&&u.call(o),0):o.next)&&!(u=u.call(o,t[1])).done)return u;switch(o=0,u&&(t=[2&t[0],u.value]),t[0]){case 0:case 1:u=t;break;case 4:return c.label++,{value:t[1],done:!1};case 5:c.label++,o=t[1],t=[0];continue;case 7:t=c.s.pop(),c.u.pop();continue;default:if(!(u=0<(u=c.u).length&&u[u.length-1])&&(6===t[0]||2===t[0])){c=0;continue}if(3===t[0]&&(!u||t[1]>u[0]&&t[1]<u[3])){c.label=t[1];break}if(6===t[0]&&c.label<u[1]){c.label=u[1],u=t;break}if(u&&c.label<u[2]){c.label=u[2],c.s.push(t);break}u[2]&&c.s.pop(),c.u.pop();continue}t=r.call(e,c)}catch(n){t=[6,n],o=0}finally{i=u=0}if(5&t[0])throw t[1];return{value:t[0]?t[1]:void 0,done:!0}}([t,n])}}},c=require("@invertase/private-notification-parser").default;module.exports=function(){return e(this,void 0,void 0,function(){function r(){return e(this,void 0,void 0,function(){var t;return u(this,function(n){switch(n.label){case 0:return[4,o.adbCmd(i,"shell dumpsys notification --noredact",{verbosity:"high"})];case 1:return t=n.o().stdout,[2,c(t).sort(function(n,t){return n.mCreationTimeMs<t.mCreationTimeMs})]}})})}var i,t,o;return u(this,function(n){return"ios"===device.getPlatform()?Object.defineProperty(device,"notifications",{get:function(){throw new Error("Notifications helpers only supported on Android")}}):(i=device._deviceId,t=device.deviceDriver,o=t.adb,Object.defineProperty(device,"notifications",{get:function(){var n=this;return{all:function(){return r()},latest:function(){return e(n,void 0,void 0,function(){return u(this,function(n){switch(n.label){case 0:return[4,r()];case 1:return[2,n.o()[0]]}})})},clear:function(){return e(n,void 0,void 0,function(){var t,e;return u(this,function(n){switch(n.label){case 0:return[4,r()];case 1:return(t=n.o()).length?[4,o.adbCmd(i,"shell input swipe 0 0 0 300",{})]:[3,3];case 2:n.o(),n.label=3;case 3:e=0,n.label=4;case 4:return e<t.length?[4,new Promise(function(n){return setTimeout(n,200)})]:[3,8];case 5:return n.o(),[4,o.adbCmd(i,"shell input swipe 0 500 400 500",{})];case 6:n.o(),n.label=7;case 7:return e++,[3,4];case 8:return[2]}})})}}}})),[2]})})};
