require 'json'
platform :ios, '10.0'
$RNFirebaseAsStaticFramework = false

appPackage = JSON.parse(File.read(File.join('..', '..', 'node_modules', '@react-native-firebase', 'app', 'package.json')))
$FirebaseSDKVersion = appPackage['sdkVersions']['ios']['firebase']

# Version override - uncomment to test overriding, otherwise take value from `@react-native-firebase/app`
# $FirebaseSDKVersion = '7.5.0'
Pod::UI.puts "react-native-firebase/tests: Using Firebase SDK version '#{$FirebaseSDKVersion}'"


require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'testing' do
  # use_frameworks!

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => $FirebaseSDKVersion
end

post_install do |installer|

  # We support a smaller range of deployment than some libraries, eliminate related noise
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end

end
