platform :ios, '10.0'
$RNFirebaseAsStaticFramework = false

# Version override testing
$FirebaseSDKVersion = '7.4.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'testing' do
  # use_frameworks!

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  #pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => $FirebaseSDKVersion
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
      config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = "NO"
      config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = "NO"
      config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
    end
  end
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "i386 arm64"
  end
end
