#!/bin/bash
# Sourced by test-rn-bare-ios-launch-smoke.sh. Launch-time assertions for the
# dynamic RNFBFirebase probe (RNFB_TEST_RN_BARE_DYNAMIC_FIREBASE=1).
#
# The probe build job proves link-time facts (otool/nm on a Release build). The
# generic launch smoke only proves a foreground UIScene window, and a missing
# RNFBFirebase.framework or a configure() that never ran would not change that
# on its own (a dyld failure aborts the launch, but a no-op configure does not).
# These assertions close that gap for the probe-built Debug app:
#   - the Pods project was generated by a probe pod install (the launch smoke
#     does not run pod install, so a flag-on smoke after a flag-off build must
#     fail rather than silently launch the shipped graph)
#   - RNFBFirebase.framework is embedded in the installed .app
#   - the app's own binary (testrnbare, or testrnbare.debug.dylib for Debug
#     previews) has an undefined symbol into the RNFBFirebase AppClient, so the
#     facade is what calls configure (any other [FIRApp configure] would also
#     log the marker below and would not prove the facade path)
#   - RNFBFirebase.framework is mapped into the running app process (dyld loaded it)
#   - the app logged FirebaseCore's "Configuring the default app." marker.
#     FirebaseCore logs that at debug level inside FIRApp configure, which is
#     the only thing RNFBFirebaseAppClient.configure() calls. The smoke passes
#     -FIRDebugEnabled at launch and streams debug-level logs so the marker is
#     visible.
#
# The caller must define `log` and `fail` (fail must exit). The loaded-image
# capture sets RNFB_PROBE_LOADED_IMAGES instead of printing, so `fail` runs in
# the caller's shell and not in a command substitution subshell.

RNFB_PROBE_LAUNCH_FRAMEWORK_REL='RNFBFirebase.framework/RNFBFirebase'
# lsof -Fn emits one "n<path>" line per mapped file. Anchor on the full line so
# only the framework binary itself matches, not RNFBFirebase.debug.dylib or a
# longer path that merely ends the same way.
RNFB_PROBE_LAUNCH_FRAMEWORK_LSOF_RE='^n.*/RNFBFirebase\.framework/RNFBFirebase$'
RNFB_PROBE_LAUNCH_CONFIGURE_MARKER='Configuring the default app.'
RNFB_PROBE_LAUNCH_CONFIGURE_CODE='I-COR000001'

# rnfb_probe_launch_assert_probe_pods <Pods.xcodeproj/project.pbxproj>
rnfb_probe_launch_assert_probe_pods() {
  local pods_pbxproj="$1"

  [[ -f "$pods_pbxproj" ]] || fail "Pods project was not found: ${pods_pbxproj}; run RNFB_TEST_RN_BARE_DYNAMIC_FIREBASE=1 yarn test-rn-bare:ios:build first"
  if ! grep -Fq 'RNFBFirebaseProbeOrder' "$pods_pbxproj"; then
    fail "probe launch smoke is on but ${pods_pbxproj} has no RNFBFirebaseProbeOrder; the last pod install was not a probe install, so this would launch the shipped graph"
  fi
  log "probe pods: RNFBFirebaseProbeOrder present"
}

# rnfb_probe_launch_assert_framework_embedded <app-dir>
rnfb_probe_launch_assert_framework_embedded() {
  local app_dir="$1"
  local binary="${app_dir}/Frameworks/${RNFB_PROBE_LAUNCH_FRAMEWORK_REL}"

  [[ -d "$app_dir" ]] || fail "app bundle was not found: ${app_dir}"
  [[ -f "$binary" ]] || fail "RNFBFirebase.framework is not embedded in ${app_dir} (missing ${binary}); dyld cannot load the probe facade"
  log "embedded: ${binary}"
}

# rnfb_probe_launch_assert_facade_referenced <app-dir>
# Requires an undefined symbol that mentions both RNFBFirebase and AppClient
# (e.g. $s12RNFBFirebase0A9AppClientO9configureyyFZ) in the app's executable or
# its Debug dylib (<name>.debug.dylib; Xcode previews put the code there).
rnfb_probe_launch_assert_facade_referenced() {
  local app_dir="$1"
  local name
  local binary
  local symbols
  local facade_symbols
  local found_binary=0

  name="$(basename "$app_dir" .app)"
  for binary in "${app_dir}/${name}.debug.dylib" "${app_dir}/${name}"; do
    [[ -f "$binary" ]] || continue
    found_binary=1
    # Capture before grep: `set -o pipefail` plus `grep -q` treats SIGPIPE as failure.
    symbols="$(nm -u "$binary" 2>/dev/null || true)"
    facade_symbols="$(grep -F 'RNFBFirebase' <<<"$symbols" || true)"
    if grep -Fq 'AppClient' <<<"$facade_symbols"; then
      log "facade referenced: ${binary} has an undefined RNFBFirebase AppClient symbol"
      return 0
    fi
  done
  if [[ "$found_binary" -eq 0 ]]; then
    fail "no app binary to inspect in ${app_dir} (looked for ${name}.debug.dylib and ${name}); cannot prove the app references the RNFBFirebase facade"
  fi
  fail "neither ${name}.debug.dylib nor ${name} in ${app_dir} references an RNFBFirebase AppClient symbol (nm -u); the app does not call the probe facade, so the configure marker would not prove the facade path"
}

# rnfb_probe_launch_capture_loaded_images <pid>
# Sets RNFB_PROBE_LOADED_IMAGES to the file paths mapped into the process
# (`lsof -Fn`, name fields only) and RNFB_PROBE_LOADED_IMAGES_ERROR when the
# listing could not be taken. Must run while the app is still alive. It never
# fails itself: the caller's existing launch assertions (key window, Firebase
# crash hints) report a dead app with more detail, and
# rnfb_probe_launch_assert_framework_loaded fails on the recorded error.
rnfb_probe_launch_capture_loaded_images() {
  local pid="$1"

  RNFB_PROBE_LOADED_IMAGES=""
  RNFB_PROBE_LOADED_IMAGES_ERROR=""
  if [[ ! "$pid" =~ ^[0-9]+$ ]]; then
    RNFB_PROBE_LOADED_IMAGES_ERROR="launch did not report a numeric pid for the app (got '${pid}')"
    return 0
  fi
  if ! RNFB_PROBE_LOADED_IMAGES="$(lsof -p "$pid" -Fn 2>&1)"; then
    RNFB_PROBE_LOADED_IMAGES_ERROR="lsof failed for pid ${pid}: ${RNFB_PROBE_LOADED_IMAGES}"
    RNFB_PROBE_LOADED_IMAGES=""
    return 0
  fi
  if [[ -z "$RNFB_PROBE_LOADED_IMAGES" ]]; then
    RNFB_PROBE_LOADED_IMAGES_ERROR="lsof returned nothing for pid ${pid}; the app exited before the load check"
  fi
}

# rnfb_probe_launch_assert_framework_loaded
# Uses RNFB_PROBE_LOADED_IMAGES from the capture above. Capture before grep:
# `set -o pipefail` plus `grep -q` treats SIGPIPE from the producer as failure.
rnfb_probe_launch_assert_framework_loaded() {
  if [[ -n "${RNFB_PROBE_LOADED_IMAGES_ERROR:-}" ]]; then
    fail "could not list mapped images, so RNFBFirebase.framework load is unproven: ${RNFB_PROBE_LOADED_IMAGES_ERROR}"
  fi
  if ! grep -Eq "$RNFB_PROBE_LAUNCH_FRAMEWORK_LSOF_RE" <<<"$RNFB_PROBE_LOADED_IMAGES"; then
    fail "RNFBFirebase.framework is not mapped into the running app process; the probe facade was not loaded by dyld"
  fi
  log "dyld: RNFBFirebase.framework is mapped into the running app"
}

# rnfb_probe_launch_assert_configure_logged <app-log>
rnfb_probe_launch_assert_configure_logged() {
  local app_log="$1"
  local matches

  [[ -f "$app_log" ]] || fail "app log was not found: ${app_log}"
  if ! matches="$(grep -F "$RNFB_PROBE_LAUNCH_CONFIGURE_CODE" "$app_log" | grep -F "$RNFB_PROBE_LAUNCH_CONFIGURE_MARKER")"; then
    fail "FirebaseCore never logged '${RNFB_PROBE_LAUNCH_CONFIGURE_MARKER}' (${RNFB_PROBE_LAUNCH_CONFIGURE_CODE}); RNFBFirebaseAppClient.configure() did not run, or debug logging was off. See ${app_log}"
  fi
  log "FirebaseCore configure marker observed:"
  printf '%s\n' "$matches" | tail -2
}
