module.exports = {
  number: 1234,
  string: 'acde',
  boolean: true,
  null: null,
  simpleObject: {
    number: 1234,
    string: 'acde',
    boolean: true,
    null: null,
  },
  simpleArray: [1234, 'acde', true, null],
  advancedObject: {
    array: [1234, 'acde', false, null],
    object: {
      number: 1234,
      string: 'acde',
      boolean: true,
      null: null,
      array: [1234, 'acde', true, null],
    },
    number: 1234,
    string: 'acde',
    boolean: true,
    null: null,
  },
  advancedArray: [
    1234,
    'acde',
    true,
    null,
    [1234, 'acde', true, null],
    {
      number: 1234,
      string: 'acde',
      boolean: true,
      null: null,
      array: [1234, 'acde', true, null],
    },
  ],
};
