blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/invertase/react-native-firebase/discussions/new
    about: Share ideas for new features.
  - name: Ask a Question
    url: https://github.com/invertase/react-native-firebase/discussions/new
    about: Ask the community for help.
  - name: Show and tell
    url: https://github.com/invertase/react-native-firebase/discussions/4106
    about: Showcase what you've built with React Native Firebase.
