/**
 * Copyright (c) 2016-present Invertase Limited & Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this library except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

import Foundation
import UIKit
#if canImport(RNFBFirebase)
import RNFBFirebase
#else
import FirebaseMessaging
#endif

/// Actual `MessagingDelegate` implementation. Deliberately `internal`
/// (Swift-default access, not `public`/`@objc`): Swift's generated
/// `RNFBMessaging-Swift.h` only contains `public`/`@objc`-visible
/// declarations, and a class's *conformance list* is part of what has to be
/// described there once a class is included. If this conformance lived on a
/// `public`/`@objcMembers` class instead (as it did in an earlier version of
/// this file), the generated header emitted
/// `@interface RNFBMessagingFIRMessagingDelegate : NSObject <FIRMessagingDelegate>`,
/// which forced the header to also add `@import FirebaseMessaging;` so
/// Objective-C could resolve `FIRMessagingDelegate` -- the exact
/// illegal-`@import`-in-`.mm` problem this whole facade refactor exists to
/// avoid, just generated by the compiler instead of hand-written. Keeping
/// this class `internal` excludes it from the generated header entirely, so
/// `.mm` files never see a Firebase type mentioned there.
///
/// Note there's deliberately no `import RNFBApp` here either: RNFBApp marks
/// all of its headers `private_header_files`, so its generated umbrella
/// header (and therefore what Swift's `import RNFBApp` can see) is empty.
/// Sending the `messaging_token_refresh` event goes through
/// `RNFBMessagingEventEmitter` (`RNFBMessaging+EventEmitter.h/.m`) instead --
/// a plain Objective-C class in *this* pod that reaches `RNFBApp`'s
/// `RNFBRCTEventEmitter` via an ordinary textual `#import`, and is itself
/// visible here because it's one of this pod's public headers (see
/// `RNFBMessaging.podspec`).
private final class RNFBMessagingDelegateImpl: NSObject, MessagingDelegate {

  private weak var originalDelegate: MessagingDelegate?

  func observe() {
    let messaging = Messaging.messaging()
    if messaging.delegate !== self {
      originalDelegate = messaging.delegate
      messaging.delegate = self
    }
  }

  // MARK: - MessagingDelegate

  // JS -> `onTokenRefresh`
  func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
    guard let fcmToken = fcmToken else {
      // Don't crash when the token is reset.
      return
    }

    RNFBMessagingEventEmitter.sendTokenRefreshEvent(token: fcmToken)

    // `originalDelegate` is weak -- capture a strong local once so it can't be
    // deallocated between the two uses below (same race the ObjC
    // UNUserNotificationCenter delegate already guards against). The
    // protocol method is `@optional` in Firebase's header, so it has to be
    // called via optional chaining (`?`) rather than `responds(to:)`.
    let strongOriginalDelegate = originalDelegate
    strongOriginalDelegate?.messaging?(messaging, didReceiveRegistrationToken: fcmToken)

    // Preserve the existing AppDelegate fallback for applications that
    // implement the callback without assigning themselves as
    // `Messaging.messaging().delegate`.
    let didReceiveRegistrationTokenSelector = NSSelectorFromString(
      "messaging:didReceiveRegistrationToken:")
    if let applicationDelegate = UIApplication.shared.delegate {
      let isOriginalDelegate =
        (strongOriginalDelegate as AnyObject?) === (applicationDelegate as AnyObject)
      if !isOriginalDelegate,
        applicationDelegate.responds(to: didReceiveRegistrationTokenSelector)
      {
        _ = applicationDelegate.perform(
          didReceiveRegistrationTokenSelector, with: messaging, with: fcmToken)
      }
    }
  }
}

/// Swift replacement for the historical Objective-C
/// `RNFBMessagingFIRMessagingDelegate` (previously
/// `RNFBMessaging+FIRMessagingDelegate.{h,m}`).
///
/// Only a thin `sharedInstance()`/`observe()` surface is `public`/`@objc`
/// here -- the real `MessagingDelegate` conformance lives on the `internal`
/// `RNFBMessagingDelegateImpl` above, kept off this type's own interface so
/// nothing Firebase-shaped leaks into the generated `-Swift.h` that `.mm`
/// files include. See that class's doc comment for why.
///
/// Exposed back to Objective-C under the same class name it always had, so
/// `RNFBMessaging+NSNotificationCenter.m` only has to change which header
/// declares it (`#import "RNFBMessaging-Swift.h"` instead of
/// `#import "RNFBMessaging+FIRMessagingDelegate.h"`), not the call site
/// (`[[RNFBMessagingFIRMessagingDelegate sharedInstance] observe]`).
@objcMembers public class RNFBMessagingFIRMessagingDelegate: NSObject {

  private static let instance = RNFBMessagingFIRMessagingDelegate()
  private static let observeLock = NSLock()
  private static var hasObserved = false

  private let impl = RNFBMessagingDelegateImpl()

  @objc public static func sharedInstance() -> RNFBMessagingFIRMessagingDelegate {
    return instance
  }

  @objc public func observe() {
    Self.observeLock.lock()
    defer { Self.observeLock.unlock() }
    guard !Self.hasObserved else {
      return
    }
    Self.hasObserved = true
    impl.observe()
  }
}
