source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

def common_pods
  # pod 'RNFirebase', :path => '../'
  # pod 'React', :path => '../node_modules/react-native'
  [
    'Firebase',
    'Firebase/Core',
    'Firebase/Auth',
    'Firebase/Storage',
    'Firebase/Database',
    'Firebase/RemoteConfig',
    'Firebase/Messaging'
  ].each do |lib|
    pod lib
  end
end

def test_pods
  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '~> 3.0.0'
end

def setup
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |configuration|
        # configuration.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
        # configuration.build_settings['CODE_SIGNING_REQUIRED'] = "YES"
        # configuration.build_settings['CODE_SIGNING_ALLOWED'] = "YES"

        target.build_settings(configuration.name)['OTHER_LDFLAGS'] = '$(inherited)'
        target.build_settings(configuration.name)['USER_HEADER_SEARCH_PATHS'] = "$(BUILT_PRODUCTS_DIR)"
        target.build_settings(configuration.name)['LD_DYLIB_INSTALL_NAME'] = '@rpath/${EXECUTABLE_NAME}'
        target.build_settings(configuration.name)['LD_RUNPATH_SEARCH_PATHS'] = '$(inherited) @rpath @loader_path/../Frameworks @executable_path/Frameworks'

        target.build_settings(configuration.name)['ONLY_ACTIVE_ARCH'] = 'NO'
        target.build_settings(configuration.name)['HEADER_SEARCH_PATHS'] = [
          "$(inherited)",
          "${PODS_ROOT}/Headers/**",
          "$(SRCROOT)/../../React/**",
          "$(SRCROOT)/../../react-native/React/**",
          '$(RN_ROOT)/React/**',
          '$(PODS_ROOT)/Headers'
        ].join(' ')
        target.build_settings(configuration.name)['FRAMEWORK_SEARCH_PATHS'] = [
          "$(inherited)",
          '$(PODS_ROOT)/**',
          '$(PODS_CONFIGURATION_BUILD_DIR)/**'
        ].join(' ')
        target.build_settings(configuration.name)['OTHER_LDFLAGS'] = "$(inherited)"
      end
    end
  end
end

# target 'RNFirebase' do
#   common_pods
#   project "RNFirebase.xcodeproj"
#   setup
# end

target 'RNFirebaseTests' do
  use_frameworks!
  common_pods
  test_pods
  pod 'React', :path => '../node_modules/react-native'
  setup
end
