name: Deploy API Reference
on:
  workflow_dispatch:
jobs:
  deploy-api-reference:
    name: 'Deploy API Reference'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
      - name: Install latest NPM
        run: |
          npm --version
          npm install -g npm@latest
          npm --version
      - name: Yarn Install
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          retry_wait_seconds: 60
          max_attempts: 3
          command: yarn
      - name: Build API reference (TypeDoc)
        run: yarn reference:api:gh-pages
      - name: Upload API reference artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./apidocs-out
