name: Firebase JS SDK Type Comparison

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
      - 'website/**'
      - '.spellcheck.dict.txt'
      - '**/*.md'

  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'website/**'
      - '.spellcheck.dict.txt'
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compare-types:
    name: Compare Types with Firebase JS SDK
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # https://github.com/actions/checkout/releases
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 50
      # https://github.com/actions/setup-node/releases
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 22
      # https://github.com/actions/cache/releases
      - uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        name: Yarn Cache Restore
        continue-on-error: true
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-v1
      - name: Yarn Install
        # https://github.com/nick-fields/retry/releases
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          timeout_minutes: 15
          retry_wait_seconds: 30
          max_attempts: 3
          command: yarn
      - name: Install Compare Types Dependencies
        run: cd .github/scripts/compare-types && yarn install
      - name: Compare Types with Firebase JS SDK
        run: cd .github/scripts/compare-types && yarn compare
      # https://github.com/actions/cache/releases
      - uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        name: Yarn Cache Save
        if: "${{ github.ref == 'refs/heads/main' }}"
        continue-on-error: true
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('yarn.lock') }}
