name: Firebase JS SDK Type Comparison

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
      - 'website/**'
      - '.spellcheck.dict.txt'
      - '**/*.md'

  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'website/**'
      - '.spellcheck.dict.txt'
      - '**/*.md'

permissions:
  contents: read
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compare-types:
    name: Compare Types with Firebase JS SDK
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # https://github.com/actions/checkout/releases
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 50
      # https://github.com/actions/setup-node/releases
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
      # https://github.com/actions/cache/releases
      - uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        name: Yarn Cache Restore
        continue-on-error: true
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-v1
      - name: Yarn Install
        # https://github.com/nick-fields/retry/releases
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          timeout_minutes: 15
          retry_wait_seconds: 30
          max_attempts: 3
          command: yarn
      - name: Install Compare Types Dependencies
        run: cd .github/scripts/compare-types && yarn install
      - name: Compare Types with Firebase JS SDK
        run: cd .github/scripts/compare-types && yarn compare
      # https://github.com/actions/cache/releases
      - uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        name: Yarn Cache Save
        if: "${{ github.ref == 'refs/heads/main' }}"
        continue-on-error: true
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('yarn.lock') }}
