name: Firebase JS SDK Type Comparison

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
      - 'website/**'
      - '.spellcheck.dict.txt'
      - '**/*.md'

  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'website/**'
      - '.spellcheck.dict.txt'
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compare-types:
    name: Compare Types with Firebase JS SDK
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 50
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/cache/restore@v4
        name: Yarn Cache Restore
        continue-on-error: true
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-v1
      - name: Yarn Install
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          retry_wait_seconds: 30
          max_attempts: 3
          command: yarn
      - name: Install Compare Types Dependencies
        run: cd .github/scripts/compare-types && yarn install
      - name: Compare Types with Firebase JS SDK
        run: cd .github/scripts/compare-types && yarn compare
      - uses: actions/cache/save@v4
        name: Yarn Cache Save
        if: "${{ github.ref == 'refs/heads/main' }}"
        continue-on-error: true
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('yarn.lock') }}
