name: Testing

on:
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
      - 'website/**'
      - '.spellcheck.dict.txt'
      - '**/*.md'
  push:
    branches:
      - main
      - v14-release
    paths-ignore:
      - 'docs/**'
      - 'website/**'
      - '.spellcheck.dict.txt'
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  jest:
    name: Jest
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      # https://github.com/actions/checkout/releases
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 50
      # https://github.com/actions/setup-node/releases
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 22
      # https://github.com/actions/cache/releases
      - uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        name: Yarn Cache Restore
        id: yarn-cache
        continue-on-error: true
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-v1
      - name: Yarn Install
        # https://github.com/nick-fields/retry/releases
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          timeout_minutes: 15
          retry_wait_seconds: 60
          max_attempts: 3
          command: yarn
      - name: Jest
        run: yarn tests:jest-coverage
      # https://github.com/codecov/codecov-action/releases
      - uses: codecov/codecov-action@3f20e214133d0983f9a10f3d63b0faf9241a3daa # v6.0.0
        with:
          verbose: true
      # https://github.com/actions/cache/releases
      - uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        name: Yarn Cache Save
        if: "${{ github.ref == 'refs/heads/main' }}"
        continue-on-error: true
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('yarn.lock') }}
